<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GtaAutoGameplay.Platform.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GtaAutoGameplay.Core\GtaAutoGameplay.Core.csproj" />
  </ItemGroup>
</Project>
